name: 'Changelog File Generator'
description: 'Generates a changelog for a release based on a YAML file'
inputs:
  changelog-directory:
    description: "The directory where the changelog files are stored. Do not include a trailing slash."
    required: true
    default: "changelog"
  release-tag-name:
    description: "The version of the release"
    required: true
runs:
  using: "composite"
  steps:
    - name: Generate changelog
      id: generate_changelog
      run: |
        sh ${{ github.action_path }}/scripts/generate_changelog.sh "${{ inputs.changelog-directory }}" "${{ inputs.release-tag-name }}" > changelog_output.md
      shell: bash
    - name: Upload changelog as artifact
      uses: actions/upload-artifact@v2
      with:
        name: changelog
        path: changelog_output.md
